// <auto-generated />
using System;
using Electro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Electro.Infrastructure.Migrations
{
    [DbContext(typeof(ElectroContext))]
    [Migration("20260927195221_Iniziale")]
    partial class Iniziale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Electro.Domain.Entities.AnagraficaUtente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Citta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceFiscale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimaModifica")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indirizzo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitaIva")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId")
                        .IsUnique();

                    b.ToTable("AnagraficheUtenti");
                });

            modelBuilder.Entity("Electro.Domain.Entities.DatiPagamentoUtente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CapFatturazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CittaFatturazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceFiscaleFatturazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodiceSdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndirizzoFatturazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartitaIvaFatturazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinciaFatturazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RagioneSociale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UtenteId")
                        .IsUnique();

                    b.ToTable("DatiPagamentoUtenti");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Impianto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInstallazione")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndirizzoInstallazione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProprietarioId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("TipoImpiantoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProprietarioId");

                    b.HasIndex("TipoImpiantoId");

                    b.ToTable("Impianti");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Materiale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrezzoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UnitaMisura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materiali");
                });

            modelBuilder.Entity("Electro.Domain.Entities.MaterialeUtilizzato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialeId")
                        .HasColumnType("int");

                    b.Property<int>("OperazioneId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrezzoUnitarioStorico")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantita")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialeId");

                    b.HasIndex("OperazioneId");

                    b.ToTable("MaterialiUtilizzati");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Operazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CostoManodopera")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DataCompletamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataIntervento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Operazioni");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataChiusura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCreazione")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImpiantoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ImportoPagato")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ImportoTotale")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MetodoPagamento")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Stato")
                        .HasColumnType("int");

                    b.Property<int>("StatoPagamento")
                        .HasColumnType("int");

                    b.Property<int>("TicketAnagraficaId")
                        .HasColumnType("int");

                    b.Property<int>("UtenteCreatoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImpiantoId");

                    b.HasIndex("TicketAnagraficaId");

                    b.HasIndex("UtenteCreatoreId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Electro.Domain.Entities.TicketAnagrafica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TicketAnagrafiche");
                });

            modelBuilder.Entity("Electro.Domain.Entities.TicketOperatore", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UtenteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAssegnazione")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResponsabilePrincipale")
                        .HasColumnType("bit");

                    b.HasKey("TicketId", "UtenteId");

                    b.HasIndex("UtenteId");

                    b.ToTable("TicketOperatori");
                });

            modelBuilder.Entity("Electro.Domain.Entities.TipoImpianto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descrizione")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAttivo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipiImpianto");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Utente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Utenti");
                });

            modelBuilder.Entity("Electro.Domain.Entities.AnagraficaUtente", b =>
                {
                    b.HasOne("Electro.Domain.Entities.Utente", "Utente")
                        .WithOne("AnagraficaUtente")
                        .HasForeignKey("Electro.Domain.Entities.AnagraficaUtente", "UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Electro.Domain.Entities.DatiPagamentoUtente", b =>
                {
                    b.HasOne("Electro.Domain.Entities.Utente", "Utente")
                        .WithOne("DatiPagamentoUtente")
                        .HasForeignKey("Electro.Domain.Entities.DatiPagamentoUtente", "UtenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Impianto", b =>
                {
                    b.HasOne("Electro.Domain.Entities.Utente", "Proprietario")
                        .WithMany("Impianti")
                        .HasForeignKey("ProprietarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Electro.Domain.Entities.TipoImpianto", "TipoImpianto")
                        .WithMany("Impianti")
                        .HasForeignKey("TipoImpiantoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proprietario");

                    b.Navigation("TipoImpianto");
                });

            modelBuilder.Entity("Electro.Domain.Entities.MaterialeUtilizzato", b =>
                {
                    b.HasOne("Electro.Domain.Entities.Materiale", "Materiale")
                        .WithMany("MaterialiUtilizzati")
                        .HasForeignKey("MaterialeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electro.Domain.Entities.Operazione", "Operazione")
                        .WithMany("MaterialiUtilizzati")
                        .HasForeignKey("OperazioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materiale");

                    b.Navigation("Operazione");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Operazione", b =>
                {
                    b.HasOne("Electro.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Operazioni")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Electro.Domain.Entities.Impianto", "Impianto")
                        .WithMany("Ticket")
                        .HasForeignKey("ImpiantoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Electro.Domain.Entities.TicketAnagrafica", "TicketAnagrafica")
                        .WithMany("Ticket")
                        .HasForeignKey("TicketAnagraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electro.Domain.Entities.Utente", "UtenteCreatore")
                        .WithMany("TicketCreati")
                        .HasForeignKey("UtenteCreatoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Impianto");

                    b.Navigation("TicketAnagrafica");

                    b.Navigation("UtenteCreatore");
                });

            modelBuilder.Entity("Electro.Domain.Entities.TicketOperatore", b =>
                {
                    b.HasOne("Electro.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Operatori")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Electro.Domain.Entities.Utente", "Utente")
                        .WithMany("TicketAssegnati")
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Impianto", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Materiale", b =>
                {
                    b.Navigation("MaterialiUtilizzati");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Operazione", b =>
                {
                    b.Navigation("MaterialiUtilizzati");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Operatori");

                    b.Navigation("Operazioni");
                });

            modelBuilder.Entity("Electro.Domain.Entities.TicketAnagrafica", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Electro.Domain.Entities.TipoImpianto", b =>
                {
                    b.Navigation("Impianti");
                });

            modelBuilder.Entity("Electro.Domain.Entities.Utente", b =>
                {
                    b.Navigation("AnagraficaUtente");

                    b.Navigation("DatiPagamentoUtente");

                    b.Navigation("Impianti");

                    b.Navigation("TicketAssegnati");

                    b.Navigation("TicketCreati");
                });
#pragma warning restore 612, 618
        }
    }
}
